
@startuml playstopFlowchart
title playstop
start
if (activeIfMethod() ) then 
    partition start {
        :終了タスクを削除; 
        if (次のタスクがあるか？) then (true)
            partition playTask() {
                repeat
                :アニメーションオブジェクト作成;
                :再生ボタン画像変更;
                :textBox非表示;
                :タイトル変更;
                partition timeCount() {
                    :timeLimitオブジェクト作成;
                    :アニメーションスタート;
                    :制限時間取得;
                    :残り時間取得;   
                    if (残り時間0秒) then 
                        :フラグを折る;
                    else if (残り時間10秒) then
                        :読み上げ;
                        :n秒アニメーション;
                    else if (残り時間がジャストn分) then
                        :読み上げ;
                    else if (残り時間がある) then
                        :次のアニメーション;
                    endif 
                    if (残り時間がある) then
                        :時間表示;
                    endif                                     
                }
                :終了タスクを削除;                
                if (次のタスクがある) then 
                    :時間の初期化;
                    :次のタスクに変える;
                endif
                repeat while (次のタスクがある)
            }
        endif
    }
else 
    partition stop {
        :再生ボタン画像変更;
        :timeLimit.stop();
        :addInput();
    }
endif
end
@enduml
